version: "3.1"

services:
  annie-pg:
    image: "postgres:14.1"
    container_name: "annie-pg"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: tiger
      POSTGRES_USER: scott
      POSTGRES_DB: annie_baby
    # command:
    #   [
    #     "--character-set-server=utf8mb4",
    #     "--collation-server=utf8mb4_unicode_ci",
    #     "--default-authentication-plugin=mysql_native_password",
    #   ]
    # network_mode: bridge
    ports:
      - "5432:5432"
    networks:
      - back
      - front

networks:
  front:
    driver: bridge
  back:

volumes:
  pgdata:
