// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// VideosColumns holds the columns for the "videos" table.
	VideosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "link", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "output_dir", Type: field.TypeString},
		{Name: "proxy", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VideosTable holds the schema information for the "videos" table.
	VideosTable = &schema.Table{
		Name:       "videos",
		Columns:    VideosColumns,
		PrimaryKey: []*schema.Column{VideosColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		VideosTable,
	}
)

func init() {
}
